global:
  resolve_timeout: 5m

route:
  receiver: "telegram"
  group_by: ["alertname"]
  repeat_interval: 30m
  group_wait: 10s
  group_interval: 5m

receivers:
  - name: "telegram"
    telegram_configs:
      - bot_token: "8218813054:AAH65NZ5vbOmSt553X0CJU6QYb8NVQa6aDM"
        chat_id: 5037781514
        parse_mode: "Markdown"
        message: |
          ðŸš¨ *{{ .Status | toUpper }}*: {{ .CommonLabels.alertname }}
          Namespace: {{ .CommonLabels.namespace }}
          Severity: {{ .CommonLabels.severity }}
          Summary: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
