global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is 1m.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. Default is 1m.

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090'] # Target Prometheus itself
  
  - job_name: 'hubble-guard'
    static_configs:
      - targets: ['172.25.93.63:8080']
    scrape_interval: 15s
    metrics_path: /metrics