apiVersion: v1
kind: Service
metadata:
  name: {{ include "hubble-guard.fullname" . }}-anomaly-detector
  namespace: hubble-guard
  labels:
    {{- include "hubble-guard.anomalyDetector.labels" . | nindent 4 }}
  {{- with .Values.anomalyDetector.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.anomalyDetector.service.type }}
  ports:
    - port: {{ .Values.anomalyDetector.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "hubble-guard.anomalyDetector.selectorLabels" . | nindent 4 }}

