{{- if .Values.apiServer.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hubble-guard.fullname" . }}-api-server
  namespace: hubble-guard
  labels:
    {{- include "hubble-guard.apiServer.labels" . | nindent 4 }}
  {{- with .Values.apiServer.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.apiServer.service.type }}
  ports:
    - port: {{ .Values.apiServer.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "hubble-guard.apiServer.selectorLabels" . | nindent 4 }}
{{- end }}

