apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hubble-guard.fullname" . }}-grafana-provisioning
  namespace: hubble-guard
  labels:
    {{- include "hubble-guard.grafana.labels" . | nindent 4 }}
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://{{ include "hubble-guard.prometheus.serviceName" . }}:{{ .Values.prometheus.service.port }}
        isDefault: true
  dashboards.yaml: |
    apiVersion: 1
    providers:
      - name: 'Hubble Dashboards'
        orgId: 1
        folder: 'Monitoring'
        type: file
        options:
          path: /var/lib/grafana/dashboards

