apiVersion: v1
kind: Namespace
metadata:
  name: hubble-guard
  labels:
    name: hubble-guard
    app.kubernetes.io/name: {{ include "hubble-guard.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}

