{{- if .Values.anomalyDetector.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "hubble-guard.serviceAccountName" . }}
  namespace: hubble-guard
  labels:
    {{- include "hubble-guard.anomalyDetector.labels" . | nindent 4 }}
  {{- with .Values.anomalyDetector.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}

